### ISSUE TITLE
Group chat full image

### ISSUE THREAD

**Issue by pointydev** [NYRI4/Discolored#13]
![dark svg](https://canary.discord.com/assets/25f3555f54d3c872f0ac7a5922c8eccf.svg)
![light svg](https://canary.discord.com/assets/e1865a8cd9d685b3f6b69d22adc9b429.svg)
![example](https://the.uwu.foundation/9Q3nWmJ.png)

thanks,
pointy

**Comment by NYRI4** [comment]
https://github.com/NYRI4/Discolored/commit/209c73a170414141acaf37c95b8c198f1bf9ea70 - This commit should have added it, thanks for the report.

**Comment by pointydev** [comment]
I don't believe this issue has been fixed by 209c73a as there is no style attribute on the targeted element, meaning no modification is applied. When using modified selectors to correct this, the image isn't the correct one anyway, resulting in the final style being broken.
```css
[class*="partyFull-"] [class*="errorStateIcon-"] /* Modified selectors */ {
    background-image: url('https://nyri4.github.io/Discolored/assets/ban_hammer.svg')!important; 
}
```
![broken result](https://the.uwu.foundation/7D8m9Kq.png)

thanks,
pointy
